version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "sympabotDB"
      POSTGRES_USER: "sympabotUSER"
      POSTGRES_PASSWORD: "sympabotPW"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "artefok2017@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "pgsympabotpassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - postgres
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # prometheus:
  #   image: prom/prometheus
  #   restart: always
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #   networks:
  #     - prometheus
  #   depends_on:
  #     - telegram_bot

  # grafana:
  #   image: grafana/grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     GF_SECURITY_ADMIN_USER: sympabot
  #     GF_SECURITY_ADMIN_PASSWORD: sympabotgrafanaPW
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - prometheus
      
volumes:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
  prometheus:
    driver: bridge